### ISSUE TITLE
Route Error

### ISSUE THREAD

**Issue by wisnubaldas** [eggysetiawan/inventory-app#1]
Hi, 
Iam from PT CJFI to review your code,

whats mean this route error,

```error
Invalid route action: [C:32:"Opis\Closure\SerializableClosure":221:{a:5:{s:3:"use";a:0:{}s:8:"function";s:55:"function () { return \redirect()->route('login'); }";s:5:"scope";s:37:"Illuminate\Routing\RouteFileRegistrar";s:4:"this";N;s:4:"self";s:32:"000000003d49ff1e0000000065709cbf";}}]
```

![image](https://user-images.githubusercontent.com/10908214/123577358-e09cc400-d7fd-11eb-9f76-a3baec030060.png)

tankx,

**Comment by eggysetiawan** [comment]
Dear Wisnu,

please inform me how did you found those errors, because i’ve check my code
and didnt find it.

or maybe you can just clone from my repo for fresh installation at
https://github.com/eggysetiawan/inventory-app.git

Best Regards,
Rahmat Setiawan

**Comment by wisnubaldas** [comment]
saya baru saja clone dari git untuk review codingan kamu, saya taro di devlop server ketika di jalanin error,
emang envirotmen yg kamu pake apa? 
http://202.51.98.140:9091/ coba cek di situ, 
banch apa sourcode kamu yg terbaru biar saya bisa tarik lagi?


rgd,

**Comment by eggysetiawan** [comment]
Terima kasih atas informasi nya Pak Wisnu.

Untuk develop environment yg saya gunakan:

sistem operasi : windows 10

menggunakan laragon
Apache 24.47 VS
mysql 5.7

selain itu sudah saya test di OS Kubuntu KDE plasma menggunakan valet

tidak ada masalah Pak

**Comment by eggysetiawan** [comment]
Dear Pak Wisnu,

saya sudah perbaiki error perihal serialize closure yang bapak alami,
Mohon berkenan untuk melakukan clone ulang pada repo saya dan melakukan
beberapa hal saat instalasi

1. Setelah melakukan composer install harap lakukan seeding database dengan
perintah
> php artisan migrate --seed

link https://github.com/eggysetiawan/inventory-app.git

Terima Kasih.

**Comment by wisnubaldas** [comment]
oh.. i see, 
push lagi aja biar saya tarik, kenapa ngga pake docker aja yg lebih mudah kemaren,

**Comment by wisnubaldas** [comment]
ok eggy udah down, tapi masih ada masalah di database nya,
kita disini make `mysql  Ver 15.1 Distrib 10.1.48-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
dia belom support sama json, 

tanks ya,

**Comment by eggysetiawan** [comment]
Sudah saya push setengah jam yang lalu Pak. Terima kasih saran nya Pak,
lain kali saya coba pakai docker
